import { Metadata } from 'next';
import CompanyDetails from './company-details';

export const generateMetadata = async ({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> => {
  return {
    title: params.slug,
    description: 'Generated by create next app',
  };
};

export default function Page({ params }: { params: { slug: string } }) {
  return (
    <>
      <CompanyDetails />
      <div>{params.slug}</div>
    </>
  );
}
