import { Metadata } from 'next';
import Resources from './resources';

export const metadata: Metadata = {
  title: 'Resource | Scope Seeker',
  description: 'Generated by create next app',
};

export default function Page() {
  return <Resources />;
}
