import { Metadata } from 'next';
import MyProfile from './my-profile';

export const metadata: Metadata = {
  title: 'My Profile | Scope Seeker',
  description: 'Generated by create next app',
};

export default function Page() {
  return <MyProfile />;
}
