import '@/styles/globals.css';
import { Metadata } from 'next';
import React from 'react';
import { Providers } from './provider';

export const metadata: Metadata = {
  title: {
    template: '%s | Scope Seeker',
    default: 'Scope Seeker',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
