import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Heading, Text, useColorMode } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {colorMode, toggleColorMode} = useColorMode()
  return (
    <>
      <Head>
        <title>Home | Scope Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Text>Hello I am Home</Text>
        <Heading color={'brand.100'}>Hello</Heading>
        <Button onClick={toggleColorMode}>
        Toggle {colorMode === 'light' ? 'Dark' : 'Light'}
        </Button>
      </main>
    </>
  )
}
