import Head from 'next/head';
import { Inter } from 'next/font/google';
import {Text} from '@chakra-ui/react'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Scope Seeker | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Text>Home</Text>
        <Link href={'/about'}>About</Link>
    </>
  );
}
