import { Metadata } from 'next';
import Dashboard from './dashboard';

export const metadata: Metadata = {
  title: 'Dashboard | Scope Seeker',
  description: 'Generated by create next app',
};

export default function Page() {
  return <Dashboard />;
}
