import { Metadata } from 'next';
import Jobs from './jobs';

export const metadata: Metadata = {
  title: 'Jobs | Scope Seeker',
  description: 'Generated by create next app',
};

export default function Page() {
  return <Jobs />;
}
